### ISSUE TITLE
Update v2 endpoint to not have as many validation options

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/tr1d1um#276]
Validation configuration will apply completely in v3.  v2 already has a fix to warn when TTL Validation doesn't pass and then default to the max TTL.  For URL validation, v2 will only enforce loopback validation (if configured).

Example configuration:
```yaml
    validation:
      url:
        httpsOnly: true
        allowLoopback: false
        allowIP: false
        allowSpecialUseHosts: false
        allowSpecialUseIPs: false
        invalidHosts: []
        invalidSubnets: []
      ttl:
        max: 1m
        jitter: 1s
```
